---
modcomments: 
  homeable: false
  required: false
  requirements: 
    liberty: 
      min: 2.1.4
  version: 0.0.0
  description: >
    Allow admins or content creators to
    moderate comments.
  license: 
    html: '<a href="http://www.gnu.org/licenses/licenses.html#LGPL">LGPL</a>'
  plugins:
    modcomments:
      handler_file: modcomments_lib.php
      api_handlers:
        function:
          content_store: modcomments_content_store
          content_list_sql: modcomments_content_list_sql
        tpl:
          content_edit_mini: 'bitpackage:modcomments/service_content_edit_mini_inc.tpl'
          content_list: 'bitpackage:modcomments/service_content_inc.tpl'
          content_body: 'bitpackage:modcomments/service_content_inc.tpl'
